version: 2
jobs:
  build:
    working_directory: ~/rpg-master-frontend
    docker:
      - image: zaknafain/rpg-master-frontend:1.0
    steps:
      - checkout
      - restore_cache:
          key: rpg-master-frontend-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: rpg-master-frontend-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npm run test:docker
