name: TSLint

on: [push]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.20.1
      uses: actions/setup-node@v1
      with:
        node-version: 12.20.1
    - name: Node module cache
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-nodeModules-${{ hashFiles('**/.nvmrc') }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nodeModules-${{ hashFiles('**/.nvmrc') }}-
          ${{ runner.os }}-nodeModules-
    - name: npm install
      run: |
        npm list || npm install --no-optional
        npm install -g @angular/cli
    - name: ng lint
      run: ng lint
